name: substitute
description: Substitute like sed.
version: 0.0.1
homepage: https://github.com/slashdotted/substitute-flutter

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: