name: substitute
description: >-
  A package that implements a substitute function for strings
  (similar to the one provided by the Unix command line tool sed).
version: 0.0.6
homepage: https://github.com/slashdotted/substitute-flutter

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  test: ^1.22.2