name: substitute
description: >-
  A package that implements a substitute function for strings
  (similar to the one provided by the Unix command line tool sed).
version: 0.0.5
homepage: https://github.com/slashdotted/substitute-flutter

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: